# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Package app project with Dev environment with it provision profile and upload to shared web page."
  lane :dev_ipa do
    # first match provision profile
    match_dev
    build_app(
      configuration: "DEV", 
      scheme: "DEV",
      export_method: "development",
      output_directory: "./builds/Dev",
      output_name: "TryJenkins_dev.ipa"
    )
  end

  desc "Package app project with QA environment with it provision profile and upload to shared web page."
  lane :qa_ipa do  
    # first match provision profile
    match_adhoc
    build_app(
      configuration: "QA", 
      scheme: "QA",
      export_method: "ad-hoc",
      output_directory: "./builds/QA",
      output_name: "TryJenkins_QA.ipa"
    )
  end

  desc "Package app project with Production environment with it provision profile and upload to web."
  lane :inhouse_ipa do 
    # first match provision profile
    match_enterprise
    build_app(
      configuration: "PROD",
      scheme: "PROD",
      export_method: "enterprise",
      output_directory: "./builds/Prod",
      output_name: "TryJenkins_Prod.ipa"
    )
  end

  desc "Run all enviroment with dev, QA, Prod to package to ipa."
  lane :all do
    dev_ipa
    qa_ipa
    inhouse_ipa
  end

  desc "Override match development use specified identifier to generate provision."
  lane :match_dev do 
    match(
    type: 'development',
    readonly: true,
    app_identifier: 'com.kinwei.TryJenkins.*'
    )
  end
  
  desc "Override match adhoc use specified identifier to generate provision."
  lane :match_adhoc do 
  match(
    type: 'adhoc',
    readonly: true,
    app_identifier: 'com.kinwei.TryJenkins.*'
  )
  end

  desc "Override match enterprise use specified identifier to generate provision."
  lane :match_enterprise do 
  match(
    type: 'enterprise',
    readonly: true,
    app_identifier: 'com.kinwei.inhouse.TryJenkins'
  )
  end

end
