# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Package app project with Dev environment with it provision profile and upload to shared web page."
  lane :dev do
    # add actions here: https://docs.fastlane.tools/actions
    build_app(
      configuration: "DEV", 
      scheme: "DEV"
    )
  end

  desc "Package app project with QA environment with it provision profile and upload to shared web page."
  lane :QA do 
    build_app(
      configuration: "QA", 
      scheme: "QA"
    )
  end

  desc "Package app project with Production environment with it provision profile and upload to web."
  lane :Prod do 
    build_app(
      configuration: "PROD",
      scheme: "PROD"
    )
  end
end
